openapi: '3.0.0'
info:
  version: 1.0.0
  title: NoteX AI API
  license:
    name: MIT
servers:
  - url: http://notex.ai/api/v1
paths:
  /meetings:
    get:
      summary: List all meetings
      operationId: listMeetings
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of meetings
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meetings'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create meeting
      operationId: createMeeting
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /meetings/{meetingId}:
    get:
      summary: Get meeting info
      operationId: showMeetingById
      parameters:
        - name: meetingId
          in: path
          required: true
          description: The id of the meeting to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meetings'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /summaries:
    get:
      summary: List all summaries
      operationId: listSummaries
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of summaries
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meetings'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create summary
      operationId: createSummary
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Meeting:
      required:
        - id
        - topic
      properties:
        id:
          type: integer
          format: int64
        topic:
          type: string
        language:
          type: string
    Meetings:
      type: array
      items:
        $ref: '#/components/schemas/Meeting'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string